<a href="https://colab.research.google.com/github/Raihan-J/Data-Compression-And-Encryption/blob/master/Advanced%20Matrix%20Operations/Advanced%20Matrix%20Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Flatten () function**

In [1]:
from numpy import asmatrix,arange

In [2]:
a = asmatrix(arange(1,10).reshape(3,3))
a

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [3]:
a.flatten()

matrix([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

**Frobenius Norm Of a Matrix**

**Assignment-1**

In [4]:
m = asmatrix(arange(1,17).reshape(4,4))
m[0,1] = 0
m[1,3] = 0
m

matrix([[ 1,  0,  3,  4],
        [ 5,  6,  7,  0],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])

In [5]:
from numpy.linalg import inv, norm
im = inv(m)
norm(im)

3.7059917700933944

**Infinty Norm**

**Assignment-2**

In [6]:
from numpy import inf
norm(im,ord=inf)

4.624999999999995

**Singular Value Decomposition (SVD)**

In [7]:
from numpy import matrix
from numpy.linalg import svd

m1 = matrix([[3,2,2],[2,3,-2]])
U,sigma,V_conjugate = svd(m1)

U

matrix([[-0.70710678, -0.70710678],
        [-0.70710678,  0.70710678]])

In [8]:
sigma

array([5., 3.])

In [9]:
V_conjugate

matrix([[-7.07106781e-01, -7.07106781e-01, -6.47932334e-17],
        [-2.35702260e-01,  2.35702260e-01, -9.42809042e-01],
        [-6.66666667e-01,  6.66666667e-01,  3.33333333e-01]])

In [10]:
from numpy import diag,allclose
from numpy.matlib import zeros
smat = zeros((2,3))

smat

matrix([[0., 0., 0.],
        [0., 0., 0.]])

In [11]:
smat[:2,:2] = diag(sigma)

smat

matrix([[5., 0., 0.],
        [0., 3., 0.]])

In [12]:
allclose(m1, U* smat *V_conjugate)

True